# Generated by Django 5.0.3 on 2025-02-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_timestamp_alter_chatroom_artist_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
    ]
