# Generated by Django 5.0.3 on 2025-02-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_artist_alter_chatroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_deleted_by_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
