# Generated by Django 5.0.3 on 2025-02-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='audio',
        ),
    ]
