# Generated by Django 5.0.3 on 2025-02-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatmessage_audio_alter_chatmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='audio',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
