# Generated by Django 5.0.3 on 2025-01-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='artist',
            new_name='username',
        ),
    ]
