# Generated by Django 5.0.3 on 2025-01-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_artist_work_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='username',
            new_name='artist',
        ),
    ]
