# Generated by Django 5.0.3 on 2025-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], default='cod', max_length=10),
        ),
    ]
