# Generated by Django 5.0.3 on 2025-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(default='30 mins', max_length=50),
        ),
    ]
