# Generated by Django 5.0.3 on 2025-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_message_chat_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artist_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profile_images/'),
        ),
    ]
