# Generated by Django 5.0.3 on 2025-02-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_artist_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='artist_profile_image',
        ),
    ]
