# Generated by Django 5.0.3 on 2025-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slots',
            field=models.JSONField(default=list),
        ),
    ]
