# Generated by Django 5.0.3 on 2025-02-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_service_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slots',
        ),
    ]
