# Generated by Django 5.0.3 on 2025-02-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='available_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='available_time',
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('available_time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.service')),
            ],
            options={
                'unique_together': {('service', 'available_date', 'available_time')},
            },
        ),
    ]
