# Generated by Django 5.0.3 on 2025-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_service_available_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artist_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profile_images/'),
        ),
    ]
