# Generated by Django 5.0.3 on 2025-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_user_is_available_user_otp_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
