# Generated by Django 5.0.3 on 2025-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], default='cod', max_length=10),
        ),
    ]
