# Generated by Django 5.0.3 on 2025-02-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_remove_booking_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='training_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
