# Generated by Django 5.0.3 on 2025-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_user_training_certificate_delete_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceavailability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
