# Generated by Django 5.0.3 on 2025-02-12 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_serviceavailability_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceavailability',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.service'),
        ),
    ]
