# Generated by Django 5.0.3 on 2025-02-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_booking_user_address_booking_user_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_longitude',
        ),
    ]
