# Generated by Django 5.0.3 on 2025-02-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_booking_latitude_booking_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceavailability',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.service'),
        ),
    ]
