# Generated by Django 5.0.3 on 2025-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_serviceavailability_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='artist_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
