# Generated by Django 5.0.3 on 2025-03-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_rename_time_booking_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='longitude',
        ),
    ]
