# Generated by Django 5.0.3 on 2025-03-02 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_booking_latitude_booking_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='work_days',
        ),
        migrations.AddField(
            model_name='workingtime',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ServiceSchedule',
        ),
    ]
