# Generated by Django 5.0.3 on 2025-03-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_remove_service_work_days_workingtime_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='work_days',
            field=models.ManyToManyField(blank=True, related_name='services', to='accounts.workingtime'),
        ),
    ]
