# Generated by Django 5.0.3 on 2025-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_booking_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
