# Generated by Django 5.0.3 on 2025-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_booking_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
