# Generated by Django 5.0.3 on 2025-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_booking_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='embedding_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
