# Generated by Django 5.0.3 on 2025-03-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_service_embedding_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='embedding_json',
        ),
    ]
