# Generated by Django 5.0.3 on 2025-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_remove_service_embedding_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
