# Generated by Django 5.0.3 on 2025-03-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_booking_refund_requested'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
